set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g default-terminal "screen-256color"

set -g status-bg colour34
set -g status-fg colour16
set-option -sg escape-time 200
set -g default-command "/bin/bash"

# Dim inactive panes
set -g window-style 'fg=colour245'
# Keep active pane with normal background
set -g window-active-style 'fg=color255'

# Set title
set -g pane-border-status top
set -g pane-border-format " #{?pane_active,*,·} (#{s/%%//:pane_id}) #{pane_title}"

# Install plugin
run-shell ${HOME}/work/tmux-resurrect/resurrect.tmux

# Save/restore per-window env vars
set -g @resurrect-hook-pre-save-all 'bash ~/.tmux/scripts/save-env.sh'
set -g @resurrect-hook-post-restore-all 'sleep 1 && bash ~/.tmux/scripts/restore-env.sh'

set -g extended-keys-format csi-u
